In [3]:
import numpy as np

# Create two custom NumPy arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Stack A and B vertically
stacked_vertically = np.vstack((A, B))

# Stack A and B horizontally
stacked_horizontally = np.hstack((A, B))

print("Stacked Vertically:")
print(stacked_vertically)

print("Stacked Horizontally:")
print(stacked_horizontally)


Stacked Vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Stacked Horizontally:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [4]:
import numpy as np

# Create two custom NumPy arrays A and B
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])

# Find the common elements between A and B
common_elements = np.intersect1d(A, B)

print("Common Elements:")
print(common_elements)


Common Elements:
[3 4 5]


In [5]:
import numpy as np

# Create a custom NumPy array A
A = np.array([2, 4, 6, 8, 10, 12, 14])

# Define the specific range (e.g., between 5 and 10)
lower_limit = 5
upper_limit = 10

# Create a boolean mask for elements within the specified range
mask = (A >= lower_limit) & (A <= upper_limit)

# Use the mask to extract elements within the range
elements_in_range = A[mask]

print("Elements within the range [{}, {}]:".format(lower_limit, upper_limit))
print(elements_in_range)


Elements within the range [5, 10]:
[ 6  8 10]


In [6]:
import numpy as np

# Define the URL and load the data into iris_2d
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

# Define the conditions for filtering
petal_length_condition = iris_2d[:, 2] > 1.5
sepal_length_condition = iris_2d[:, 0] < 5.0

# Combine the conditions using logical AND (&) to filter the rows
filtered_rows = iris_2d[petal_length_condition & sepal_length_condition]

print("Filtered Rows:")
print(filtered_rows)


Filtered Rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [7]:
import pandas as pd

# Read the CSV data into a DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter every 20th row starting from the 1st row (row 0)
filtered_data = df.iloc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_data)


IndexError: .iloc requires numeric indexers, got ['Manufacturer' 'Model' 'Type']

In [8]:
import pandas as pd

# Read the CSV data into a DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Calculate the mean for 'Min.Price' and 'Max.Price' columns
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

# Replace missing values with their respective means
df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)

# Display the DataFrame with missing values replaced
print(df)


   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [9]:
import pandas as pd
import numpy as np

# Create a DataFrame with random integer values
data = np.random.randint(10, 40, 60).reshape(-1, 4)
df = pd.DataFrame(data)

# Calculate the row sums
row_sums = df.sum(axis=1)

# Get the rows where the sum is greater than 100
rows_with_sum_gt_100 = df[row_sums > 100]

# Display the rows
print(rows_with_sum_gt_100)


     0   1   2   3
1   38  35  24  15
4   34  22  22  29
5   32  33  36  22
7   22  31  33  15
9   17  21  38  34
10  29  37  19  36
11  23  39  17  29
12  12  38  24  27
